<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    public function run(): void
    {
        $produk = [
            [
                'kategori_id' => 1,
                'nama_produk' => 'Putu Mayang',
                'harga' => 25000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Gethuk',
                'harga' => 25000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Tahu isi Sayur',
                'harga' => 25000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Apem',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Puli',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Tortila/Happytos',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Cendol Keju',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kacang Telor',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Stik Bawang',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Gado-gado Tela ',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kerupuk Ikan',
                'harga' => 2500,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kuro Jadul',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kuro Jeruk',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kuro Jambu Merah',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kuro Jambu Hijau',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kuro Apel Merah',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kuro Apel Hijau',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Arem-arem',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Sosis SOlo',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Risoles Bihun',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Lumpia Bihun',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Donat',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Misoa',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Awug-awug gula aren',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Awug-awug mutiara',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Lepet Jagung',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Nogosari bandung (bunga)',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Jentik manis Jagung (bunga)',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Jentik manis mutiara (bunga)',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Nogosari Daun',
                'harga' => 30000,
                'deskripsi' => 'Nagasari dengan isian pisang pipit',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Bikang',
                'harga' => 30000,
                'deskripsi' => 'Bikang dengan motif bunga',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Tahu Bacem',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Tahu Fantasi Telur Puyuh',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Putri Ayu',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Ketan Srundeng',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Ketan Kelapa Gula Aren',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Ketan Tolo',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Dadar gulung Pink',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Pisang goreng crispy (Pisang Pipit)',
                'harga' => 30000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Soes Kering',
                'harga' => 28000,
                'deskripsi' => 'Lumpia isi rebung dan ayam',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Peyek Kacang Tanah',
                'harga' => 28000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
             [
                'kategori_id' => 1,
                'nama_produk' => 'Peyek Kacang Hijau',
                'harga' => 3000,
                'deskripsi' => '',
                'min_order' => 50,
            ],
            
            //KATEGORI 2
            [
                'kategori_id' => 2,
                'nama_produk' => 'Jajanan Godogan Kecil',
                'harga' => 45000,
                'deskripsi' => 'Paket jajanan godogan nampan mika dengan isian pisang, kacang rebus, ubi kuning, ubi, dan jagung',
                'min_order' => 10,
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Snack Mini isi 100',
                'harga' => 300000,
                'deskripsi' => 'Paket Snack Mini yang menyediakan putri mandi, kuro jambu merah, kroket, bolu gulung hijau, dan sosis solo',
                'min_order' => 2,
            ],
             [
                'kategori_id' => 2,
                'nama_produk' => 'Paket Jajan Godogan 1',
                'harga' => 180000,
                'deskripsi' => 'Paket dengan isian pisang, kacang rebus, ubi kuning, ubi ungu, jagung, talas rebus',
                'min_order' => 1,
            ],
              [
                'kategori_id' => 2,
                'nama_produk' => 'Paket Jajan Godogan 2',
                'harga' => 180000,
                'deskripsi' => 'Paket dengan isian pisang, kacang rebus, ubi kuning, ubi ungu, jagung, singkong rebus',
                'min_order' => 1,
            ],
              [
                'kategori_id' => 2,
                'nama_produk' => 'Paket Gethuk',
                'harga' => 250000,
                'deskripsi' => 'Paket dengan isian gethuk, tiwul, sentiling pisang, ketan tolo, klepon, puli, gobet',
                'min_order' => 2,
            ],
             [
                'kategori_id' => 2,
                'nama_produk' => 'Snack Mini isi 150',
                'harga' => 425000,
                'deskripsi' => 'Paket Snack Mini yang menyediakan putri mandi, kuro jambu merah, kroket, bolu gulung hijau, dan sosis solo',
                'min_order' => 1,
            ],
             [
                'kategori_id' => 2,
                'nama_produk' => 'Snack Mini 100 Paket A',
                'harga' => 300000,
                'deskripsi' => 'Paket Snack Mini yang menyediakan putri mandi, kuro jambu merah, kroket, bolu gulung hijau, dan sosis solo',
                'min_order' => 2,
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Snack Mini 100 Paket B',
                'harga' => 300000,
                'deskripsi' => 'Paket Snack Mini yang menyediakan bugis daun, lepet jagung, kuro apel merah, kroket, dan sosis solo',
                'min_order' => 2,
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Snack Mini 100 Paket C',
                'harga' => 300000,
                'deskripsi' => 'Paket Snack Mini yang menyediakan Semar mendem, kuro apel hijau, kroket, jentik manis jagung, dan sosis solo',
                'min_order' => 2,
            ],
        ];
        
        foreach ($produk as $item) {
            DB::table('produk')->insert($item);
        }
    }
}